# Generated by Django 5.0.6 on 2024-07-03 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last update time')),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('interview_round', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('position_title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('applied', 'Applied'), ('no_response', 'No Response'), ('interviewing', 'Interviewing'), ('offer_stage', 'Offer Stage'), ('rejected_applicant', 'Rejected (Applicant Withdrew)'), ('rejected_company', 'Rejected (Company Decision)')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_tracker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobTrackerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last update time')),
                ('current_status', models.CharField(choices=[('draft', 'Draft'), ('applied', 'Applied'), ('no_response', 'No Response'), ('interviewing', 'Interviewing'), ('offer_stage', 'Offer Stage'), ('rejected_applicant', 'Rejected (Applicant Withdrew)'), ('rejected_company', 'Rejected (Company Decision)')], max_length=20)),
                ('previous_status', models.CharField(choices=[('draft', 'Draft'), ('applied', 'Applied'), ('no_response', 'No Response'), ('interviewing', 'Interviewing'), ('offer_stage', 'Offer Stage'), ('rejected_applicant', 'Rejected (Applicant Withdrew)'), ('rejected_company', 'Rejected (Company Decision)')], max_length=20)),
                ('job_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.jobtracker')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
