# Generated by Django 5.0.6 on 2024-07-08 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_alter_jobtracker_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobtracker',
            options={'ordering': ['-created_at']},
        ),
    ]
