# Generated by Django 5.0.6 on 2024-07-10 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0004_alter_jobtracker_options'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtracker',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_tracker_set', to='core.country'),
        ),
        migrations.AlterField(
            model_name='jobtracker',
            name='status',
            field=models.CharField(blank=True, choices=[('accepted_offer', 'Accepted Offer'), ('applied', 'Applied'), ('draft', 'Draft'), ('offer_stage', 'Offer Stage'), ('interviewing', 'Interviewing'), ('no_response', 'No Response'), ('rejected_applicant', 'Rejected (Applicant Withdrew)'), ('rejected_company', 'Rejected (Company Decision)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobtrackerhistory',
            name='current_status',
            field=models.CharField(choices=[('accepted_offer', 'Accepted Offer'), ('applied', 'Applied'), ('draft', 'Draft'), ('offer_stage', 'Offer Stage'), ('interviewing', 'Interviewing'), ('no_response', 'No Response'), ('rejected_applicant', 'Rejected (Applicant Withdrew)'), ('rejected_company', 'Rejected (Company Decision)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobtrackerhistory',
            name='previous_status',
            field=models.CharField(choices=[('accepted_offer', 'Accepted Offer'), ('applied', 'Applied'), ('draft', 'Draft'), ('offer_stage', 'Offer Stage'), ('interviewing', 'Interviewing'), ('no_response', 'No Response'), ('rejected_applicant', 'Rejected (Applicant Withdrew)'), ('rejected_company', 'Rejected (Company Decision)')], max_length=20),
        ),
    ]
