# Generated by Django 5.0.6 on 2024-07-10 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0005_jobtracker_country_alter_jobtracker_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobtracker',
            old_name='company_name',
            new_name='organization_name',
        ),
    ]
