# Generated by Django 3.2.7 on 2021-10-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_resumetemplate_puppeteer_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumetemplate',
            name='puppeteer_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
