# Generated by Django 3.2.7 on 2021-11-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_resumetemplate_puppeteer_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberpreference',
            name='web_app_dark_mode',
        ),
        migrations.AddField(
            model_name='memberpreference',
            name='ui_mode',
            field=models.CharField(blank=True, choices=[('dark', 'dark'), ('light', 'light'), ('system', 'system')], default='system', max_length=20),
        ),
    ]
