[tool.bandit]
exclude_dirs = ["migrations", "node_modules", "venv"]
skips = ["B101"]

[tool.black]
color = true
line_length = 119
target_version = ["py39"]

[tool.isort]
color_output = true
line_length = 119
multi_line_output = 3
profile = "black"
py_version = 39

[tool.pytest.ini_options]
addopts = "-ra --verbose"
testpaths = ["test"]

[tool.coverage.run]
branch = true
omit = ["seoul/__main__.py"]
source = ["seoul"]

[tool.coverage.report]
show_missing = true
exclude_lines = ["if __name__ == .__main__.:"]
