[tool.black]
line_length = 119
target_version = ["py39"]
exclude = "/(\\.direnv|\\.eggs|\\.git|\\.hg|\\.mypy_cache|\\.nox|\\.tox|\\.venv|venv|\\.svn|_build|buck-out|build|dist|migrations)/"
color_output = true

[tool.isort]
profile = "black"
multi_line_output = 3
py_version = 39
src_paths = ["app", "dev", "docker"]
line_length = 119
color_output = true
