[tool.black]
line_length = 119
target_version = ["py39"]
exclude = """/(
    \\.eggs
    |\\.git
    |\\.hg
    |\\.venv
    |venv
    |build
    |dist
    |migrations
    |node_modules
)/"""
color_output = true

[tool.isort]
profile = "black"
multi_line_output = 3
py_version = 39
src_paths = ["confetti", "docker", "scripts", "manage.py"]
line_length = 119
color_output = true
