# Generated by Django 3.2.7 on 2021-10-30 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last update time')),
                ('download_url', models.CharField(blank=True, max_length=250, null=True)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_resume', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'member résumé',
                'verbose_name_plural': 'member résumés',
            },
        ),
    ]
