# Generated by Django 3.2.7 on 2022-02-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportedLocale',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last update time')),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('locale_tag', models.CharField(blank=True, max_length=20, unique=True)),
                ('iso_639_1_code', models.CharField(blank=True, max_length=2)),
                ('iso_639_2_code', models.CharField(blank=True, max_length=3)),
                ('name', models.CharField(blank=True, max_length=150, unique=True)),
                ('native_name', models.CharField(blank=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'supported locale',
                'verbose_name_plural': 'supported locales',
            },
        ),
        migrations.RemoveField(
            model_name='locale',
            name='language',
        ),
        migrations.RemoveField(
            model_name='country',
            name='calling_code',
        ),
        migrations.RemoveField(
            model_name='country',
            name='capital',
        ),
        migrations.RemoveField(
            model_name='country',
            name='internet_tld',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='decimal_places',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='major_unit',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='minor_unit',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Locale',
        ),
    ]
