# Generated by Django 3.2.7 on 2022-02-12 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timezone',
            options={'ordering': ('offset_minutes',), 'verbose_name': 'time zone', 'verbose_name_plural': 'time zones'},
        ),
    ]
