services:
  db:
    image: postgres:14.12
    environment:
      - "POSTGRES_DB=app"
      - "POSTGRES_PASSWORD=postgres"
  app:
    build:
      context: ../
      dockerfile: docker/app/app.production.dockerfile
    env_file:
      - ../.env
    depends_on:
      - db
    ports:
      - "0.0.0.0:8000:8000"
