# Generated by Django 3.2.7 on 2021-10-30 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import confetti.apps.member.models.preference


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last update time')),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='name of employment type')),
            ],
            options={
                'verbose_name': 'employment type',
                'verbose_name_plural': 'employment types',
            },
        ),
        migrations.CreateModel(
            name='LanguageProficiencyLevel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last update time')),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='name of language proficiency level')),
                ('value', models.PositiveIntegerField(blank=True, verbose_name='mathematical value')),
            ],
            options={
                'verbose_name': 'language proficiency level',
                'verbose_name_plural': 'language proficiency levels',
                'ordering': ('value',),
            },
        ),
        migrations.CreateModel(
            name='PortfolioTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last update time')),
                ('name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='name of template')),
            ],
            options={
                'verbose_name': 'portfolio template',
                'verbose_name_plural': 'portfolio templates',
            },
        ),
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last update time')),
                ('name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='name of template')),
                ('template_file_name', models.CharField(blank=True, max_length=150, unique=True, verbose_name='name of file containing template definition')),
                ('puppeteer_config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'resume template',
                'verbose_name_plural': 'resume templates',
            },
        ),
        migrations.CreateModel(
            name='SkillProficiencyLevel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last update time')),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='name of skill proficiency level')),
                ('value', models.PositiveIntegerField(blank=True, verbose_name='mathematical value')),
            ],
            options={
                'verbose_name': 'skill proficiency level',
                'verbose_name_plural': 'skill proficiency levels',
                'ordering': ('value',),
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last update time')),
                ('company', models.CharField(blank=True, max_length=150, verbose_name='company')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='additional information')),
                ('end_date', models.DateField(blank=True, default=None, null=True, verbose_name='end date')),
                ('is_ongoing', models.BooleanField(blank=True, default=False, verbose_name='currently working')),
                ('job_title', models.CharField(blank=True, max_length=150, verbose_name='job title')),
                ('location', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='location of company')),
                ('start_date', models.DateField(blank=True, verbose_name='start date')),
                ('employment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_type_work_experience_set', to='member.employmenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_work_experience_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'work experience',
                'verbose_name_plural': 'work experiences',
            },
        ),
        migrations.CreateModel(
            name='WebLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last update time')),
                ('href', models.CharField(blank=True, max_length=250, verbose_name='target address')),
                ('label', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='text to display')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_web_link_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'web link',
                'verbose_name_plural': 'web links',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last update time')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='name of skill')),
                ('proficiency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proficiency_skill_set', to='member.skillproficiencylevel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_skill_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last update time')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='additional information')),
                ('publication_date', models.DateField(blank=True, default=None, null=True, verbose_name='publication date')),
                ('publisher', models.CharField(blank=True, max_length=150, verbose_name='publisher')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='title')),
                ('url', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='url')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_publication_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'publication',
                'verbose_name_plural': 'publications',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last update time')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='additional information')),
                ('end_date', models.DateField(blank=True, default=None, null=True, verbose_name='end date')),
                ('is_ongoing', models.BooleanField(blank=True, default=False, verbose_name='ongoing')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='name')),
                ('start_date', models.DateField(blank=True, verbose_name='start date')),
                ('url', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='url')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_project_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
        migrations.CreateModel(
            name='MemberPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last update time')),
                ('web_app_dark_mode', models.BooleanField(blank=True, default=False)),
                ('portfolio_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_preference_set', to='member.portfoliotemplate')),
                ('resume_template', models.ForeignKey(default=confetti.apps.member.models.preference.get_default_resume_template, on_delete=django.db.models.deletion.PROTECT, related_name='member_preference_set', to='member.resumetemplate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'member preference',
                'verbose_name_plural': 'member preference',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last update time')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name of language')),
                ('proficiency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proficiency_language_set', to='member.languageproficiencylevel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_language_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
            },
        ),
        migrations.CreateModel(
            name='HonorOrAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last update time')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='additional information')),
                ('issue_date', models.DateField(blank=True, default=None, null=True, verbose_name='issue date')),
                ('issuer', models.CharField(blank=True, max_length=150, verbose_name='issuer')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_honor_or_award_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user honor or award',
                'verbose_name_plural': 'user honors or awards',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last update time')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='additional information')),
                ('issue_date', models.DateField(blank=True, default=None, null=True, verbose_name='issue date')),
                ('issuer', models.CharField(blank=True, max_length=150, verbose_name='issuer')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_certification_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user certification',
                'verbose_name_plural': 'user certifications',
            },
        ),
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last update time')),
                ('degree', models.CharField(blank=True, max_length=150, verbose_name='degree')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='additional information')),
                ('end_date', models.DateField(blank=True, default=None, null=True, verbose_name='end date')),
                ('field_of_study', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='field of study')),
                ('grade', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='grade')),
                ('is_ongoing', models.BooleanField(blank=True, default=False, verbose_name='currently studying')),
                ('location', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='location of school')),
                ('school', models.CharField(blank=True, max_length=150, verbose_name='school')),
                ('start_date', models.DateField(blank=True, verbose_name='start date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_academic_record_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'academic record',
                'verbose_name_plural': 'academic records',
            },
        ),
    ]
