# Generated by Django 3.2.7 on 2021-10-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumetemplate',
            name='puppeteer_config',
            field=models.JSONField(),
        ),
    ]
