# Generated by Django 4.0.2 on 2022-02-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last update time')),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('iso_3166_1_alpha_2_code', models.CharField(blank=True, max_length=2, unique=True)),
                ('iso_3166_1_alpha_3_code', models.CharField(blank=True, max_length=3, unique=True)),
                ('iso_3166_1_numeric_code', models.CharField(blank=True, max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=150, unique=True)),
                ('formal_name', models.CharField(blank=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last update time')),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('iso_4217_code', models.CharField(blank=True, max_length=3, unique=True)),
                ('iso_4217_numeric_code', models.CharField(blank=True, max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
                ('symbol', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'currency',
                'verbose_name_plural': 'currencies',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last update time')),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'gender',
                'verbose_name_plural': 'genders',
            },
        ),
        migrations.CreateModel(
            name='SupportedLocale',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last update time')),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('locale_tag', models.CharField(blank=True, max_length=20, unique=True)),
                ('iso_639_1_code', models.CharField(blank=True, max_length=2)),
                ('iso_639_2_code', models.CharField(blank=True, max_length=3)),
                ('name', models.CharField(blank=True, max_length=150, unique=True)),
                ('native_name', models.CharField(blank=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'supported locale',
                'verbose_name_plural': 'supported locales',
            },
        ),
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last update time')),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(blank=True, db_index=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=150, unique=True)),
                ('offset_display_text', models.CharField(blank=True, max_length=20)),
                ('offset_text', models.CharField(blank=True, max_length=20)),
                ('offset_text_clean', models.CharField(blank=True, db_index=True, max_length=20)),
                ('offset_minutes', models.SmallIntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'time zone',
                'verbose_name_plural': 'time zones',
                'ordering': ('offset_minutes',),
            },
        ),
    ]
