# Generated by Django 4.0.3 on 2022-03-04 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('id',), 'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ('id',), 'verbose_name': 'currency', 'verbose_name_plural': 'currencies'},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'ordering': ('id',), 'verbose_name': 'gender', 'verbose_name_plural': 'genders'},
        ),
        migrations.AlterModelOptions(
            name='supportedlocale',
            options={'ordering': ('id',), 'verbose_name': 'supported locale', 'verbose_name_plural': 'supported locales'},
        ),
    ]
