# Generated by Django 3.2.7 on 2021-12-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberresume',
            name='download_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='memberresume',
            name='version',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
