# Generated by Django 4.0.2 on 2022-02-20 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import seoul.apps.storage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creation time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="last update time")),
                (
                    "pdf",
                    models.FileField(
                        blank=True,
                        max_length=300,
                        null=True,
                        upload_to=seoul.apps.storage.models.generate_resume_upload_path,
                    ),
                ),
                ("version", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="resume", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "résumé",
                "verbose_name_plural": "résumés",
            },
        ),
    ]
