# Generated by Django 5.0.6 on 2024-07-07 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import app.apps.profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_record_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='honororaward',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honor_or_award_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='language',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='language',
            name='proficiency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proficiency_language_set', to='profile.languageproficiencylevel'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skill',
            name='proficiency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proficiency_skill_set', to='profile.skillproficiencylevel'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='portfolio_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_preference_set', to='profile.portfoliotemplate'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='resume_template',
            field=models.ForeignKey(default=app.apps.profile.models.get_default_resume_template, on_delete=django.db.models.deletion.PROTECT, related_name='user_preference_set', to='profile.resumetemplate'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weblink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_link_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='employment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_type_work_experience_set', to='profile.employmenttype'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
