# Generated by Django 5.0.7 on 2024-07-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('CASUAL', 'Casual'), ('FULL_TIME', 'Full-time'), ('CONTRACT', 'Contract/Fixed term'), ('PART_TIME', 'Part-time'), ('TRAINEE', 'Trainee/Apprentice')], max_length=50),
        ),
        migrations.AlterField(
            model_name='language',
            name='proficiency',
            field=models.CharField(blank=True, choices=[('ELEMENTARY', 'Elementary Proficiency'), ('LIMITED_WORKING', 'Limited Working Proficiency'), ('PROFESSIONAL', 'Professional Working Proficiency'), ('FULL_PROFESSIONAL', 'Full Professional Proficiency'), ('NATIVE', 'Native/Bilingual Proficiency')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='portfolio_template',
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.CharField(blank=True, choices=[('novice', 'Novice'), ('advanced_beginner', 'Advanced Beginner'), ('competent', 'Competent'), ('proficient', 'Proficient'), ('expert', 'Expert')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='ui_mode',
            field=models.CharField(blank=True, choices=[('DARK', 'Dark'), ('LIGHT', 'Light'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20),
        ),
        migrations.DeleteModel(
            name='EmploymentType',
        ),
        migrations.DeleteModel(
            name='LanguageProficiencyLevel',
        ),
        migrations.DeleteModel(
            name='PortfolioTemplate',
        ),
        migrations.DeleteModel(
            name='SkillProficiencyLevel',
        ),
    ]
