# Generated by Django 5.0.6 on 2024-07-07 17:39

from django.db import migrations, models

import app.apps.storage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last update time')),
                ('pdf', models.FileField(blank=True, max_length=300, null=True, upload_to=app.apps.storage.models.generate_resume_upload_path)),
                ('version', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'résumé',
                'verbose_name_plural': 'résumés',
            },
        ),
    ]
