name: ci


on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
  release:
    types:
      - created


jobs:
  test:
    if: github.event_name != 'release'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.7'
      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --requirement requirements.txt
      # - name: Test
      #   env:
      #     AWS_S3_REGION_NAME: ${{ secrets.AWS_S3_REGION_NAME }}
      #     AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
      #     AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
      #     AWS_S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
      #   run: make test

  release:
    if: github.event_name == 'push' && contains(github.ref, 'refs/heads/master')
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          node-version: '3.9.7'
      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --requirement requirements.txt
      - name: Create release
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: node dev/scripts/gh-release.py

  dockerize:
    if: github.event_name == 'release'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: myfolab/confetti
          tags: |
            type=ref,event=tag
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/confetti.prod.dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
